#cloud-config

package_update: true
package_upgrade: true

packages:
  - nginx

users:
  - name: ubuntu
    plain_text_passwd: 'ubuntu'
    lock_passwd: false
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
chpasswd:
  expire: false
ssh_pwauth: true

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - ln -s /var/www/html /home/ubuntu/www
  - chown -R ubuntu:ubuntu /var/www/html
